export interface LegalDocument {
  title: string;
  intro: string;
  sections: { heading: string; body: string }[];
}

export const TERMS: LegalDocument = {
  title: "Terms & conditions",
  intro:
    "These terms cover your use of Jaisara, how cashback is earned and paid, and what happens when an order is refunded or a claim cannot be verified.",
  sections: [
    { heading: "1. What Jaisara is", body: "Jaisara is an affiliate rewards platform. We may receive a commission when you buy a prop firm challenge through an eligible Jaisara coupon or tracked link. Cashback and Club rewards are funded from Jaisara’s commercial revenue, including that commission; they are promotional rewards, not payments made by the prop firm to you. We are not a prop firm, broker, or financial adviser." },
    { heading: "2. Eligible purchases", body: "A purchase earns cashback only if it is tracked to a Jaisara coupon or referral link at the time of checkout, and only for products listed on the deal page. Renewals, resets and add-ons earn cashback where the deal card says so." },
    { heading: "3. Claims and verification", body: "Claims may be submitted automatically, by uploading a receipt, or by entering the order details manually. We verify each claim against the firm’s commission report. Claims that cannot be matched within 45 days are rejected, and you will be told why." },
    { heading: "4. Pending and available balance", body: "Approved cashback is held as Pending until the applicable firm refund window closes. It then becomes Available and can be withdrawn. Refunded, charged-back or fraudulent orders reverse the cashback." },
    { heading: "5. Payouts", body: "The current minimum, network fee and enabled payout methods are shown before you submit a withdrawal. Gift cards cannot be refunded or exchanged once delivered. You are responsible for checking the selected network and destination address." },
    { heading: "6. Jaisara Club referrals", body: "Members earn a share of the cashback generated by people they refer. This share is paid from the platform’s portion of the commission and never reduces the referred member’s cashback. Self-referral, fake accounts and paid-traffic abuse forfeit all rewards." },
    { heading: "7. Risk notice", body: "Prop firm challenges involve fees and trading risk. Nothing on Jaisara is financial advice or a recommendation to trade. You are solely responsible for your trading decisions." },
    { heading: "8. Changes and contact", body: "We may update these terms; material changes are announced in the dashboard. Questions go to support through the in-app assistant, which escalates to a human where needed." },
  ],
};

export const PRIVACY: LegalDocument = {
  title: "Privacy policy",
  intro:
    "What we collect, why we collect it, and how to get it deleted. In short: enough to pay you correctly, and nothing sold to anyone.",
  sections: [
    { heading: "1. Data we collect", body: "Account data (email, name, country, and a profile photo if you add one), claim data (firm, plan, amount, order id, uploaded receipts), payout data (wallet address or gift card email), and basic product analytics such as pages viewed and clicks on deals." },
    { heading: "2. Why we use it", body: "To match your purchase to partner records, administer rewards, calculate referral rewards, prevent fraud, and answer support requests. Jaisara has commercial affiliate relationships with some listed firms and may receive commission on eligible tracked purchases. Receipts are read by an automated parser and by our review team when a claim needs manual checks." },
    { heading: "3. Sharing", body: "We share the minimum necessary with prop firms to verify a purchase, with payment and gift card providers to deliver payouts, and with infrastructure providers who host the service. We do not sell personal data." },
    // The receipt sentence is worded to match what actually happens: storage
    // expires an object twelve months after it was written, and it has no way
    // to know when a claim settled. Promising "after settlement" described a
    // mechanism that does not exist.
    { heading: "4. Retention", body: "Claim and payout records are kept for seven years for accounting. Uploaded receipts and files attached to support tickets are deleted twelve months after they are uploaded - the claim itself, its amount and its outcome stay on your account. Analytics data is aggregated after ninety days." },
    { heading: "5. Your rights", body: "You can export or delete your account data from the dashboard, or by asking support. Removing your profile photo deletes the stored image, and deleting your account deletes it too. Deleting an account cancels any pending cashback that has not yet cleared." },
    { heading: "6. Cookies", body: "We use a session cookie to keep you signed in and a referral cookie that records who invited you for thirty days. No third-party advertising cookies." },
  ],
};

/** The four points the entry gate summarises before asking for acceptance. */
export const GATE_POINTS = [
  "Cashback is credited only when the purchase is tracked to a Jaisara coupon or link.",
  "Pending amounts clear after the applicable firm's refund window and are void on refunds.",
  "Referral rewards are calculated separately and never reduce the reward of the person you invited.",
  "Trading a prop firm challenge carries risk. Nothing here is financial advice.",
];

/** Bump when the terms change materially - re-prompts everyone. */
export const TERMS_VERSION = "2026-08-01";
export const TERMS_STORAGE_KEY = "jaisara-terms";
